### ISSUE TITLE
Configuracion para correr `rake twitter:scan`

### ISSUE THREAD

**Issue by pel-daniel** [civica-digital/quake-relief-cdmx#43]
El rake task require sidekiq y credenciales para el API de twitter. 
Me marca un error al intentar levantar sidekiq:
```
getaddrinfo: nodename nor servname provided, or not known
```
Necesito agregar algo para configuración ?

**Comment by ghost** [comment]
lo estás corriendo con `bundle exec sidekiq` ? @pel-daniel ?

**Comment by ghost** [comment]
tienes `redis` instalado? le pasaste el `REDIS_URL` env variable?

**Comment by pel-daniel** [comment]
Si lo estoy corriendo con `bundle exec sidekiq` y también tengo redis instalado.
No le estoy pasando la ENV `REDIS_URL` en donde lo tengo que poner @MrOutis ??

**Comment by ghost** [comment]
`REDIS_URL=redis://localhost:6379`, esa variable la utiliza `config/initializers/sidekiq.rb` y la puedes poner en tu `~/.bashrc` o `~/.zshrc` el proyecto no tiene `dotenv` ni `figaro` entonces no hay algo en el proyecto que las cargue por ti, si quieres puedes agregar esas gemas ;)

**Comment by pel-daniel** [comment]
👍 va ya vi que esta en `config/initializers/sidekiq.rb`, también agrego figaro después.
Gracias @MrOutis

**Comment by ghost** [comment]
chido, @pel-daniel, gracias por tu interés; cualquier cosa abres otro issue ✌️
