### ISSUE TITLE
Como usuario al dar click a una temática veo la información para poder ayudar

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/quake-relief-cdmx#9]
![screen shot 2017-09-20 at 2 13 43 am](https://user-images.githubusercontent.com/6033705/30627892-6fa8ab98-9da9-11e7-805b-0d7e272fa7f5.png)

Veo: 
- Temática 
- Número de personas apoyando 
- Localización de la ayuda
- Botón de "Quiero ayudar" 
- Tweets

**Comment by pel-daniel** [comment]
Lo estoy checando 🎉
